-- Datos de ejemplo para desarrollo local (supabase start / supabase db reset).
-- Vacío en Fase 0: el perfil financiero inicial (ingresos, deudas, tarjetas,
-- etc., ver docs/ARQUITECTURA.md) se sembrará aquí a partir de la Fase 1,
-- cuando existan las tablas correspondientes. Nunca se hardcodea en código
-- TypeScript (secc. 40 del prompt maestro): solo vive en filas de datos.
